<?php

return [
    'ru'=>[
        "code"=>"ru",
        "latitude"=>"61.52",
        "longitude"=>"105.31",
        "icon"=>"",
        "en"=>"Russian Federation",
        "ko"=>"러시아",
        "ja"=>"ロシア"
    ],
    'us'=>[
        "code"=>"us",
        "latitude"=>"38.8977",
        "longitude"=>"-77.0365",
        "icon"=>"",
        "en"=>"United States",
        "ko"=>"미국",
        "ja"=>"アメリカ合衆国"
    ],
    'id'=>[
        "code"=>"id",
        "latitude"=>"-0.7893",
        "longitude"=>"113.9213",
        "icon"=>"",
        "en"=>"Indonesia",
        "ko"=>"인도네시아",
        "ja"=>"インドネシア"
    ],
    'au'=>[
        "code"=>"au",
        "latitude"=>"-25.2744",
        "longitude"=>"133.7751",
        "icon"=>"",
        "en"=>"Australia",
        "ko"=>"호주",
        "ja"=>"オーストラリア"
    ],
    'uk'=>[
        "code"=>"uk",
        "latitude"=>"55.3781",
        "longitude"=>"-3.4360",
        "icon"=>"",
        "en"=>"United Kingdom",
        "ko"=>"영국",
        "ja"=>"イギリス"
    ],
    'es'=>[
        "code"=>"es",
        "latitude"=>"40.4637",
        "longitude"=>"-3.7492",
        "icon"=>"",
        "en"=>"Spain",
        "ko"=>"스페인",
        "ja"=>"スペイン"
    ],
    'fr'=>[
        "code"=>"fr",
        "latitude"=>"46.2276",
        "longitude"=>"2.2137",
        "icon"=>"",
        "en"=>"France",
        "ko"=>"프랑스",
        "ja"=>"フランス"
    ],
    'ca'=>[
        "code"=>"ca",
        "latitude"=>"56.1304",
        "longitude"=>"-106.3468",
        "icon"=>"",
        "en"=>"Canada",
        "ko"=>"캐나다",
        "ja"=>"カナダ"
    ],
    'pl'=>[
        "code"=>"pl",
        "latitude"=>"51.9194",
        "longitude"=>"19.1451",
        "icon"=>"",
        "en"=>"Poland",
        "ko"=>"폴란드",
        "ja"=>"ポーランド"
    ],
    'tr'=>[
        "code"=>"tr",
        "latitude"=>"38.9637",
        "longitude"=>"35.2433",
        "icon"=>"",
        "en"=>"Turkey",
        "ko"=>"터키",
        "ja"=>"トルコ"
    ],
    'se'=>[
        "code"=>"se",
        "latitude"=>"60.1282",
        "longitude"=>"18.6435",
        "icon"=>"",
        "en"=>"Sweden",
        "ko"=>"스웨덴",
        "ja"=>"スウェーデン"
    ],
    'il'=>[
        "code"=>"il",
        "latitude"=>"31.0461",
        "longitude"=>"34.8516",
        "icon"=>"",
        "en"=>"Israel",
        "ko"=>"이스라엘",
        "ja"=>"イスラエル"
    ],
    'it'=>[
        "code"=>"it",
        "latitude"=>"41.8719",
        "longitude"=>"12.5674",
        "icon"=>"",
        "en"=>"Italy",
        "ko"=>"이탈리아",
        "ja"=>"イタリア"
    ],
    'nz'=>[
        "code"=>"nz",
        "latitude"=>"-40.9006",
        "longitude"=>"174.8860",
        "icon"=>"",
        "en"=>"New Zealand",
        "ko"=>"뉴질랜드",
        "ja"=>"ニュージーランド"
    ],
    'de'=>[
        "code"=>"de",
        "latitude"=>"51.1657",
        "longitude"=>"10.4515",
        "icon"=>"",
        "en"=>"Germany",
        "ko"=>"독일",
        "ja"=>"ドイツ"
    ],
    'af'=>[
        "code"=>"af",
        "latitude"=>"33.9391",
        "longitude"=>"67.7100",
        "icon"=>"",
        "en"=>"Afghanistan",
        "ko"=>"아프가니스탄",
        "ja"=>"アフガニスタン"
    ],
    'ala'=>[
        "code"=>"ala",
        "latitude"=>"60.1785",
        "longitude"=>"19.9156",
        "icon"=>"",
        "en"=>"Aland Islands",
        "ko"=>"올란드 제도",
        "ja"=>"オーランド諸島"
    ],
    'al'=>[
        "code"=>"al",
        "latitude"=>"41.1533",
        "longitude"=>"20.1683",
        "icon"=>"",
        "en"=>"Albania",
        "ko"=>"알바니아",
        "ja"=>"アルバニア"
    ],
    'gba'=>[
        "code"=>"gba",
        "latitude"=>"49.7077",
        "longitude"=>"-2.2070",
        "icon"=>"",
        "en"=>"Alderney",
        "ko"=>"올더니",
        "ja"=>"オルダニー"
    ],
    'dz'=>[
        "code"=>"dz",
        "latitude"=>"36.7538",
        "longitude"=>"3.0588",
        "icon"=>"",
        "en"=>"Algeria",
        "ko"=>"알제리",
        "ja"=>"アルジェリア"
    ],
    'as'=>[
        "code"=>"as",
        "latitude"=>"-14.2710",
        "longitude"=>"-170.1322",
        "icon"=>"",
        "en"=>"American Samoa",
        "ko"=>"아메리칸사모아",
        "ja"=>"アメリカ領サモア"
    ],
    'ad'=>[
        "code"=>"ad",
        "latitude"=>"42.5063",
        "longitude"=>"1.5218",
        "icon"=>"",
        "en"=>"Andorra",
        "ko"=>"안도라",
        "ja"=>"アンドラ"
    ],
    'ao'=>[
        "code"=>"ao",
        "latitude"=>"-11.2027",
        "longitude"=>"17.8739",
        "icon"=>"",
        "en"=>"Angola",
        "ko"=>"앙골라",
        "ja"=>"アンゴラ"
    ],
    'ai'=>[
        "code"=>"ai",
        "latitude"=>"18.2206",
        "longitude"=>"-63.0686",
        "icon"=>"",
        "en"=>"Anguilla",
        "ko"=>"앵귈라",
        "ja"=>"アンギラ"
    ],
    'aq'=>[
        "code"=>"aq",
        "latitude"=>"-75.2509",
        "longitude"=>"0.0000",
        "icon"=>"",
        "en"=>"Antarctica",
        "ko"=>"남극",
        "ja"=>"南極大陸"
    ],
    'ag'=>[
        "code"=>"ag",
        "latitude"=>"17.0608",
        "longitude"=>"-61.7964",
        "icon"=>"",
        "en"=>"Antigua and Barbuda",
        "ko"=>"앤티가 바부다",
        "ja"=>"アンティグア・バーブーダ"
    ],
    'ar'=>[
        "code"=>"ar",
        "latitude"=>"-38.4161",
        "longitude"=>"-63.6167",
        "icon"=>"",
        "en"=>"Argentina",
        "ko"=>"아르헨티나",
        "ja"=>"アルゼンチン"
    ],
    'am'=>[
        "code"=>"am",
        "latitude"=>"40.0691",
        "longitude"=>"45.0382",
        "icon"=>"",
        "en"=>"Armenia",
        "ko"=>"아르메니아",
        "ja"=>"アルメニア"
    ],
    'aw'=>[
        "code"=>"aw",
        "latitude"=>"12.5211",
        "longitude"=>"-69.9683",
        "icon"=>"",
        "en"=>"Aruba",
        "ko"=>"아루바",
        "ja"=>"アルバ"
    ],
    'asc'=>[
        "code"=>"asc",
        "latitude"=>"-7.9467",
        "longitude"=>"-14.3559",
        "icon"=>"",
        "en"=>"Ascension Island",
        "ko"=>"어센션 섬",
        "ja"=>"アセンション島"
    ],
    'at'=>[
        "code"=>"at",
        "latitude"=>"47.5162",
        "longitude"=>"14.5501",
        "icon"=>"",
        "en"=>"Austria",
        "ko"=>"오스트리아",
        "ja"=>"オーストリア"
    ],
    'az'=>[
        "code"=>"az",
        "latitude"=>"40.1431",
        "longitude"=>"47.5769",
        "icon"=>"",
        "en"=>"Azerbaijan",
        "ko"=>"아제르바이잔",
        "ja"=>"アゼルバイジャン"
    ],
    'bs'=>[
        "code"=>"bs",
        "latitude"=>"24.2534",
        "longitude"=>"-76.2633",
        "icon"=>"",
        "en"=>"Bahamas",
        "ko"=>"바하마",
        "ja"=>"バハマ"
    ],
    'bh'=>[
        "code"=>"bh",
        "latitude"=>"25.9304",
        "longitude"=>"50.6378",
        "icon"=>"",
        "en"=>"Bahrain",
        "ko"=>"바레인",
        "ja"=>"バーレーン"
    ],
    'bd'=>[
        "code"=>"bd",
        "latitude"=>"23.6850",
        "longitude"=>"90.3563",
        "icon"=>"",
        "en"=>"Bangladesh",
        "ko"=>"방글라데시",
        "ja"=>"バングラデシュ"
    ],
    'bb'=>[
        "code"=>"bb",
        "latitude"=>"13.1939",
        "longitude"=>"-59.5432",
        "icon"=>"",
        "en"=>"Barbados",
        "ko"=>"바베이도스",
        "ja"=>"バルバドス"
    ],
    'by'=>[
        "code"=>"by",
        "latitude"=>"53.7098",
        "longitude"=>"27.9534",
        "icon"=>"",
        "en"=>"Belarus",
        "ko"=>"벨라루스",
        "ja"=>"ベラルーシ"
    ],
    'be'=>[
        "code"=>"be",
        "latitude"=>"50.5039",
        "longitude"=>"4.4699",
        "icon"=>"",
        "en"=>"Belgium",
        "ko"=>"벨기에",
        "ja"=>"ベルギー"
    ],
    'bz'=>[
        "code"=>"bz",
        "latitude"=>"17.1899",
        "longitude"=>"-88.4976",
        "icon"=>"",
        "en"=>"Belize",
        "ko"=>"벨리즈",
        "ja"=>"ベリーズ"
    ],
    'bj'=>[
        "code"=>"bj",
        "latitude"=>"9.3077",
        "longitude"=>"2.3158",
        "icon"=>"",
        "en"=>"Benin",
        "ko"=>"베냉",
        "ja"=>"ベナン"
    ],
    'bm'=>[
        "code"=>"bm",
        "latitude"=>"32.3214",
        "longitude"=>"-64.7573",
        "icon"=>"",
        "en"=>"Bermuda",
        "ko"=>"버뮤다",
        "ja"=>"バミューダ"
    ],
    'bt'=>[
        "code"=>"bt",
        "latitude"=>"27.5142",
        "longitude"=>"90.4336",
        "icon"=>"",
        "en"=>"Bhutan",
        "ko"=>"부탄",
        "ja"=>"ブータン"
    ],
    'bo'=>[
        "code"=>"bo",
        "latitude"=>"-16.8350",
        "longitude"=>"-65.2045",
        "icon"=>"",
        "en"=>"Bolivia",
        "ko"=>"볼리비아",
        "ja"=>"ボリビア"
    ],
    'ba'=>[
        "code"=>"ba",
        "latitude"=>"43.9159",
        "longitude"=>"17.6791",
        "icon"=>"",
        "en"=>"Bosnia and Herzegovina",
        "ko"=>"보스니아 헤르체고비나",
        "ja"=>"ボスニア・ヘルツェゴビナ"
    ],
    'bw'=>[
        "code"=>"bw",
        "latitude"=>"-22.3285",
        "longitude"=>"24.6849",
        "icon"=>"",
        "en"=>"Botswana",
        "ko"=>"보츠와나",
        "ja"=>"ボツワナ"
    ],
    'bv'=>[
        "code"=>"bv",
        "latitude"=>"-54.4232",
        "longitude"=>"3.3708",
        "icon"=>"",
        "en"=>"Bouvet Island",
        "ko"=>"부베 섬",
        "ja"=>"ブーベ島"
    ],
    'br'=>[
        "code"=>"br",
        "latitude"=>"-14.2350",
        "longitude"=>"-51.9253",
        "icon"=>"",
        "en"=>"Brazil",
        "ko"=>"브라질",
        "ja"=>"ブラジル"
    ],
    'io'=>[
        "code"=>"io",
        "latitude"=>"-6.3432",
        "longitude"=>"71.8765",
        "icon"=>"",
        "en"=>"British Indian Ocean Territory",
        "ko"=>"영국령 인도양 지역",
        "ja"=>"イギリス領インド洋地域"
    ],
    'bn'=>[
        "code"=>"bn",
        "latitude"=>"4.5353",
        "longitude"=>"114.7298",
        "icon"=>"",
        "en"=>"Brunei Darussalam",
        "ko"=>"브루나이",
        "ja"=>"ブルネイ"
    ],
    'bg'=>[
        "code"=>"bg",
        "latitude"=>"42.7339",
        "longitude"=>"23.3219",
        "icon"=>"",
        "en"=>"Bulgaria",
        "ko"=>"불가리아",
        "ja"=>"ブルガリア"
    ],
    'bf'=>[
        "code"=>"bf",
        "latitude"=>"12.2383",
        "longitude"=>"-1.5616",
        "icon"=>"",
        "en"=>"Burkina Faso",
        "ko"=>"부르키나파소",
        "ja"=>"ブルキナファソ"
    ],
    'bi'=>[
        "code"=>"bi",
        "latitude"=>"-3.3733",
        "longitude"=>"29.9189",
        "icon"=>"",
        "en"=>"Burundi",
        "ko"=>"부룬디",
        "ja"=>"ブルンジ"
    ],
    'kh'=>[
        "code"=>"kh",
        "latitude"=>"12.5657",
        "longitude"=>"104.9910",
        "icon"=>"",
        "en"=>"Cambodia",
        "ko"=>"캄보디아",
        "ja"=>"カンボジア"
    ],
    'cm'=>[
        "code"=>"cm",
        "latitude"=>"7.3697",
        "longitude"=>"12.3155",
        "icon"=>"",
        "en"=>"Cameroon",
        "ko"=>"카메룬",
        "ja"=>"カメルーン"
    ],
    'ca'=>[
        "code"=>"ca",
        "latitude"=>"56.1304",
        "longitude"=>"-106.3468",
        "icon"=>"",
        "en"=>"Canada",
        "ko"=>"캐나다",
        "ja"=>"カナダ"
    ],
    'cv'=>[
        "code"=>"cv",
        "latitude"=>"16.0020",
        "longitude"=>"-24.6057",
        "icon"=>"",
        "en"=>"Cape Verde",
        "ko"=>"카보베르데",
        "ja"=>"カーボベルデ"
    ],
    'ky'=>[
        "code"=>"ky",
        "latitude"=>"19.3133",
        "longitude"=>"-81.3742",
        "icon"=>"",
        "en"=>"Cayman Islands",
        "ko"=>"케이맨 제도",
        "ja"=>"ケイマン諸島"
    ],
    'cf'=>[
        "code"=>"cf",
        "latitude"=>"6.6111",
        "longitude"=>"20.9394",
        "icon"=>"",
        "en"=>"Central African Republic",
        "ko"=>"중앙아프리카공화국",
        "ja"=>"中央アフリカ共和国"
    ],
    'td'=>[
        "code"=>"td",
        "latitude"=>"15.4730",
        "longitude"=>"18.7322",
        "icon"=>"",
        "en"=>"Chad",
        "ko"=>"차드",
        "ja"=>"チャド"
    ],
    'cl'=>[
        "code"=>"cl",
        "latitude"=>"-35.6751",
        "longitude"=>"-71.5430",
        "icon"=>"",
        "en"=>"Chile",
        "ko"=>"칠레",
        "ja"=>"チリ"
    ],
    'cn'=>[
        "code"=>"cn",
        "latitude"=>"35.8617",
        "longitude"=>"104.1954",
        "icon"=>"",
        "en"=>"China",
        "ko"=>"중국",
        "ja"=>"中国"
    ],
    'cx'=>[
        "code"=>"cx",
        "latitude"=>"-10.4475",
        "longitude"=>"105.6904",
        "icon"=>"",
        "en"=>"Christmas Island",
        "ko"=>"크리스마스 섬",
        "ja"=>"クリスマス島"
    ],
    'cc'=>[
        "code"=>"cc",
        "latitude"=>"-12.1642",
        "longitude"=>"96.8710",
        "icon"=>"",
        "en"=>"Cocos (Keeling) Islands",
        "ko"=>"코코스 제도",
        "ja"=>"ココス諸島"
    ],
    'co'=>[
        "code"=>"co",
        "latitude"=>"4.5709",
        "longitude"=>"-74.2973",
        "icon"=>"",
        "en"=>"Colombia",
        "ko"=>"콜롬비아",
        "ja"=>"コロンビア"
    ],
    'km'=>[
        "code"=>"km",
        "latitude"=>"-11.6639",
        "longitude"=>"43.3519",
        "icon"=>"",
        "en"=>"Comoros",
        "ko"=>"코모로",
        "ja"=>"コモロ"
    ],
    'cg'=>[
        "code"=>"cg",
        "latitude"=>"-0.4297",
        "longitude"=>"15.2828",
        "icon"=>"",
        "en"=>"Congo",
        "ko"=>"콩고",
        "ja"=>"コンゴ"
    ],
    'cd'=>[
        "code"=>"cd",
        "latitude"=>"-4.0383",
        "longitude"=>"21.7587",
        "icon"=>"",
        "en"=>"Congo, Democratic Republic of the",
        "ko"=>"콩고 민주 공화국",
        "ja"=>"コンゴ民主共和国"
    ],
    'ck'=>[
        "code"=>"ck",
        "latitude"=>"-21.2367",
        "longitude"=>"-159.7777",
        "icon"=>"",
        "en"=>"Cook Islands",
        "ko"=>"쿡 제도",
        "ja"=>"クック諸島"
    ],
    'cr'=>[
        "code"=>"cr",
        "latitude"=>"9.7489",
        "longitude"=>"-83.7534",
        "icon"=>"",
        "en"=>"Costa Rica",
        "ko"=>"코스타리카",
        "ja"=>"コスタリカ"
    ],
    'ci'=>[
        "code"=>"ci",
        "latitude"=>"6.8046",
        "longitude"=>"-5.2794",
        "icon"=>"",
        "en"=>"Cote D'Ivoire",
        "ko"=>"코트디부아르",
        "ja"=>"コートジボワール"
    ],
    'hr'=>[
        "code"=>"hr",
        "latitude"=>"45.1009",
        "longitude"=>"15.2073",
        "icon"=>"",
        "en"=>"Croatia",
        "ko"=>"크로아티아",
        "ja"=>"クロアチア"
    ],
    'cu'=>[
        "code"=>"cu",
        "latitude"=>"21.5218",
        "longitude"=>"-77.7812",
        "icon"=>"",
        "en"=>"Cuba",
        "ko"=>"쿠바",
        "ja"=>"キューバ"
    ],
    'cy'=>[
        "code"=>"cy",
        "latitude"=>"35.1264",
        "longitude"=>"33.4299",
        "icon"=>"",
        "en"=>"Cyprus",
        "ko"=>"키프로스",
        "ja"=>"キプロス"
    ],
    'cz'=>[
        "code"=>"cz",
        "latitude"=>"49.8175",
        "longitude"=>"15.4730",
        "icon"=>"",
        "en"=>"Czech Republic",
        "ko"=>"체코",
        "ja"=>"チェコ"
    ],
    'dk'=>[
        "code"=>"dk",
        "latitude"=>"56.2639",
        "longitude"=>"9.5018",
        "icon"=>"",
        "en"=>"Denmark",
        "ko"=>"덴마크",
        "ja"=>"デンマーク"
    ],
    'dj'=>[
        "code"=>"dj",
        "latitude"=>"11.8251",
        "longitude"=>"42.5903",
        "icon"=>"",
        "en"=>"Djibouti",
        "ko"=>"지부티",
        "ja"=>"ジブチ"
    ],
    'dm'=>[
        "code"=>"dm",
        "latitude"=>"15.4955",
        "longitude"=>"-61.3790",
        "icon"=>"",
        "en"=>"Dominica",
        "ko"=>"도미니카",
        "ja"=>"ドミニカ"
    ],
    'do'=>[
        "code"=>"do",
        "latitude"=>"18.7357",
        "longitude"=>"-70.1627",
        "icon"=>"",
        "en"=>"Dominican Republic",
        "ko"=>"도미니카 공화국",
        "ja"=>"ドミニカ共和国"
    ],
    'ec'=>[
        "code"=>"ec",
        "latitude"=>"-1.8312",
        "longitude"=>"-78.1834",
        "icon"=>"",
        "en"=>"Ecuador",
        "ko"=>"에콰도르",
        "ja"=>"エクアドル"
    ],
    'eg'=>[
        "code"=>"eg",
        "latitude"=>"26.8206",
        "longitude"=>"30.8025",
        "icon"=>"",
        "en"=>"Egypt",
        "ko"=>"이집트",
        "ja"=>"エジプト"
    ],
    'sv'=>[
        "code"=>"sv",
        "latitude"=>"13.7942",
        "longitude"=>"-88.8966",
        "icon"=>"",
        "en"=>"El Salvador",
        "ko"=>"엘살바도르",
        "ja"=>"エルサルバドル"
    ],
    'gq'=>[
        "code"=>"gq",
        "latitude"=>"1.6066",
        "longitude"=>"12.2484",
        "icon"=>"",
        "en"=>"Equatorial Guinea",
        "ko"=>"적도 기니",
        "ja"=>"赤道ギニア"
    ],
    'er'=>[
        "code"=>"er",
        "latitude"=>"15.1794",
        "longitude"=>"39.7823",
        "icon"=>"",
        "en"=>"Eritrea",
        "ko"=>"에리트레아",
        "ja"=>"エリトリア"
    ],
    'ee'=>[
        "code"=>"ee",
        "latitude"=>"58.5953",
        "longitude"=>"25.0136",
        "icon"=>"",
        "en"=>"Estonia",
        "ko"=>"에스토니아",
        "ja"=>"エストニア"
    ],
    'et'=>[
        "code"=>"et",
        "latitude"=>"8.8381",
        "longitude"=>"39.2636",
        "icon"=>"",
        "en"=>"Ethiopia",
        "ko"=>"에티오피아",
        "ja"=>"エチオピア"
    ],
    'fk'=>[
        "code"=>"fk",
        "latitude"=>"-51.7963",
        "longitude"=>"-59.5236",
        "icon"=>"",
        "en"=>"Falkland Islands",
        "ko"=>"포클랜드 제도",
        "ja"=>"フォークランド諸島"
    ],
    'fo'=>[
        "code"=>"fo",
        "latitude"=>"62.0079",
        "longitude"=>"-6.7906",
        "icon"=>"",
        "en"=>"Faroe Islands",
        "ko"=>"페로 제도",
        "ja"=>"フェロー諸島"
    ],
    'fj'=>[
        "code"=>"fj",
        "latitude"=>"-17.7134",
        "longitude"=>"178.0650",
        "icon"=>"",
        "en"=>"Fiji",
        "ko"=>"피지",
        "ja"=>"フィジー"
    ],
    'fi'=>[
        "code"=>"fi",
        "latitude"=>"65.0124",
        "longitude"=>"25.4658",
        "icon"=>"",
        "en"=>"Finland",
        "ko"=>"핀란드",
        "ja"=>"フィンランド"
    ],
    'fr'=>[
        "code"=>"fr",
        "latitude"=>"46.4144",
        "longitude"=>"2.4388",
        "icon"=>"",
        "en"=>"France",
        "ko"=>"프랑스",
        "ja"=>"フランス"
    ],
    'gf'=>[
        "code"=>"gf",
        "latitude"=>"3.9339",
        "longitude"=>"-53.1258",
        "icon"=>"",
        "en"=>"French Guiana",
        "ko"=>"프랑스령 기아나",
        "ja"=>"フランス領ギアナ"
    ],
    'pf'=>[
        "code"=>"pf",
        "latitude"=>"-17.6297",
        "longitude"=>"-149.4068",
        "icon"=>"",
        "en"=>"French Polynesia",
        "ko"=>"프랑스령 폴리네시아",
        "ja"=>"フランス領ポリネシア"
    ],
    'tf'=>[
        "code"=>"tf",
        "latitude"=>"-49.2804",
        "longitude"=>"69.3486",
        "icon"=>"",
        "en"=>"French Southern Territories",
        "ko"=>"프랑스령 남부와 남극 지역",
        "ja"=>"フランス領南方・南極地域"
    ],
    'ga'=>[
        "code"=>"ga",
        "latitude"=>"-0.8037",
        "longitude"=>"11.6094",
        "icon"=>"",
        "en"=>"Gabon",
        "ko"=>"가봉",
        "ja"=>"ガボン"
    ],
    'gm'=>[
        "code"=>"gm",
        "latitude"=>"13.4432",
        "longitude"=>"-16.5782",
        "icon"=>"",
        "en"=>"Gambia",
        "ko"=>"감비아",
        "ja"=>"ガンビア"
    ],
    'ge'=>[
        "code"=>"ge",
        "latitude"=>"41.7151",
        "longitude"=>"44.8275",
        "icon"=>"",
        "en"=>"Georgia",
        "ko"=>"조지아",
        "ja"=>"ジョージア"
    ],
    'de'=>[
        "code"=>"de",
        "latitude"=>"51.1657",
        "longitude"=>"10.4515",
        "icon"=>"",
        "en"=>"Germany",
        "ko"=>"독일",
        "ja"=>"ドイツ"
    ],
    'gh'=>[
        "code"=>"gh",
        "latitude"=>"7.9465",
        "longitude"=>"-1.0232",
        "icon"=>"",
        "en"=>"Ghana",
        "ko"=>"가나",
        "ja"=>"ガーナ"
    ],
    'gi'=>[
        "code"=>"gi",
        "latitude"=>"36.1377",
        "longitude"=>"-5.3456",
        "icon"=>"",
        "en"=>"Gibraltar",
        "ko"=>"지브롤터",
        "ja"=>"ジブラルタル"
    ],
    'gr'=>[
        "code"=>"gr",
        "latitude"=>"39.0742",
        "longitude"=>"21.8243",
        "icon"=>"",
        "en"=>"Greece",
        "ko"=>"그리스",
        "ja"=>"ギリシャ"
    ],
    'gl'=>[
        "code"=>"gl",
        "latitude"=>"71.7069",
        "longitude"=>"-42.6043",
        "icon"=>"",
        "en"=>"Greenland",
        "ko"=>"그린란드",
        "ja"=>"グリーンランド"
    ],
    'gd'=>[
        "code"=>"gd",
        "latitude"=>"12.1165",
        "longitude"=>"-61.6790",
        "icon"=>"",
        "en"=>"Grenada",
        "ko"=>"그레나다",
        "ja"=>"グレナダ"
    ],
    'gp'=>[
        "code"=>"gp",
        "latitude"=>"16.2651",
        "longitude"=>"-61.5540",
        "icon"=>"",
        "en"=>"Guadeloupe",
        "ko"=>"과들루프",
        "ja"=>"グアドループ"
    ],
    'gu'=>[
        "code"=>"gu",
        "latitude"=>"13.4432",
        "longitude"=>"-16.5782",
        "icon"=>"",
        "en"=>"Guam",
        "ko"=>"괌",
        "ja"=>"グム"
    ],
    'gt'=>[
        "code"=>"gt",
        "latitude"=>"15.7835",
        "longitude"=>"-90.2308",
        "icon"=>"",
        "en"=>"Guatemala",
        "ko"=>"과테말라",
        "ja"=>"グアテマラ"
    ],
    'gn'=>[
        "code"=>"gn",
        "latitude"=>"9.9456",
        "longitude"=>"-9.6966",
        "icon"=>"",
        "en"=>"Guinea",
        "ko"=>"기니",
        "ja"=>"ギニア"
    ],
    'gw'=>[
        "code"=>"gw",
        "latitude"=>"11.8037",
        "longitude"=>"-15.1804",
        "icon"=>"",
        "en"=>"Guinea-Bissau",
        "ko"=>"기니비사우",
        "ja"=>"ギニアビサウ"
    ],
    'gy'=>[
        "code"=>"gy",
        "latitude"=>"4.8606",
        "longitude"=>"-58.9301",
        "icon"=>"",
        "en"=>"Guyana",
        "ko"=>"가이아나",
        "ja"=>"ガイアナ"
    ],
    'ht'=>[
        "code"=>"ht",
        "latitude"=>"18.9712",
        "longitude"=>"-72.2852",
        "icon"=>"",
        "en"=>"Haiti",
        "ko"=>"아이티",
        "ja"=>"ハイチ"
    ],
    'hm'=>[
        "code"=>"hm",
        "latitude"=>"-53.0818",
        "longitude"=>"73.5042",
        "icon"=>"",
        "en"=>"Heard and McDonald Islands",
        "ko"=>"허드 맥도널드 제도",
        "ja"=>"ハード島とマクドナルド諸島"
    ],
    'hn'=>[
        "code"=>"hn",
        "latitude"=>"15.1999",
        "longitude"=>"-86.2419",
        "icon"=>"",
        "en"=>"Honduras",
        "ko"=>"온두라스",
        "ja"=>"ホンジュラス"
    ],
    'hk'=>[
        "code"=>"hk",
        "latitude"=>"22.3964",
        "longitude"=>"114.1095",
        "icon"=>"",
        "en"=>"Hong Kong",
        "ko"=>"홍콩",
        "ja"=>"香港"
    ],
    'hu'=>[
        "code"=>"hu",
        "latitude"=>"47.1625",
        "longitude"=>"19.5033",
        "icon"=>"",
        "en"=>"Hungary",
        "ko"=>"헝가리",
        "ja"=>"ハンガリー"
    ],
    'is'=>[
        "code"=>"is",
        "latitude"=>"65.0511",
        "longitude"=>"-19.2946",
        "icon"=>"",
        "en"=>"Iceland",
        "ko"=>"아이슬란드",
        "ja"=>"アイスランド"
    ],
    'in'=>[
        "code"=>"in",
        "latitude"=>"20.5937",
        "longitude"=>"78.9629",
        "icon"=>"",
        "en"=>"India",
        "ko"=>"인도",
        "ja"=>"インド"
    ],
    'id'=>[
        "code"=>"id",
        "latitude"=>"-0.7893",
        "longitude"=>"113.9213",
        "icon"=>"",
        "en"=>"Indonesia",
        "ko"=>"인도네시아",
        "ja"=>"インドネシア"
    ],
    'ir'=>[
        "code"=>"ir",
        "latitude"=>"32.4279",
        "longitude"=>"53.6880",
        "icon"=>"",
        "en"=>"Iran",
        "ko"=>"이란",
        "ja"=>"イラン"
    ],
    'iq'=>[
        "code"=>"iq",
        "latitude"=>"33.2332",
        "longitude"=>"43.6993",
        "icon"=>"",
        "en"=>"Iraq",
        "ko"=>"이라크",
        "ja"=>"イラク"
    ],
    'ie'=>[
        "code"=>"ie",
        "latitude"=>"53.4129",
        "longitude"=>"-8.2439",
        "icon"=>"",
        "en"=>"Ireland",
        "ko"=>"아일랜드",
        "ja"=>"アイルランド"
    ],
    'il'=>[
        "code"=>"il",
        "latitude"=>"31.0461",
        "longitude"=>"34.8516",
        "icon"=>"",
        "en"=>"Israel",
        "ko"=>"이스라엘",
        "ja"=>"イスラエル"
    ],
    'it'=>[
        "code"=>"it",
        "latitude"=>"41.8719",
        "longitude"=>"12.5674",
        "icon"=>"",
        "en"=>"Italy",
        "ko"=>"이탈리아",
        "ja"=>"イタリア"
    ],
    'jm'=>[
        "code"=>"jm",
        "latitude"=>"18.1426",
        "longitude"=>"-77.2975",
        "icon"=>"",
        "en"=>"Jamaica",
        "ko"=>"자메이카",
        "ja"=>"ジャマイカ"
    ],
    'jp'=>[
        "code"=>"jp",
        "latitude"=>"36.2048",
        "longitude"=>"138.2529",
        "icon"=>"",
        "en"=>"Japan",
        "ko"=>"일본",
        "ja"=>"日本"
    ],
    'jo'=>[
        "code"=>"jo",
        "latitude"=>"31.2462",
        "longitude"=>"36.5275",
        "icon"=>"",
        "en"=>"Jordan",
        "ko"=>"요르단",
        "ja"=>"ヨルダン"
    ],
    'kz'=>[
        "code"=>"kz",
        "latitude"=>"48.0196",
        "longitude"=>"66.9237",
        "icon"=>"",
        "en"=>"Kazakhstan",
        "ko"=>"카자흐스탄",
        "ja"=>"カザフスタン"
    ],
    'ke'=>[
        "code"=>"ke",
        "latitude"=>"-0.0236",
        "longitude"=>"37.9062",
        "icon"=>"",
        "en"=>"Kenya",
        "ko"=>"케냐",
        "ja"=>"ケニア"
    ]
];
