<?php

return [
    'ar'=>[
        'name'=>"العربية",
        'ko'=>"아랍어",
        'en'=>"Arabic",
        'ja'=>"アラビア語",
        'fr'=>"arabe",
        'de'=>"Arabisch",
        'code'=>"ar-XA"
    ],
    'bg'=>[
        'name'=>"български",
        'ko'=>"불가리아어",
        'en'=>"Bulgarian",
        'ja'=>"ブルガリア語",
        'fr'=>"bulgare",
        'de'=>"Bulgarisch",
        'code'=>"bg"
    ],
    'hr'=>[
        'name'=>"Croatian",
        'ko'=>"크로아티아어",
        'en'=>"Croatian",
        'ja'=>"クロアチア語",
        'fr'=>"croate",
        'de'=>"Kroatisch",
        'code'=>"hr"
    ],
    'cs'=>[
        'name'=>"Czech",
        'ko'=>"체코어",
        'en'=>"Czech",
        'ja'=>"チェコ語",
        'fr'=>"tchèque",
        'de'=>"Tschechisch",
        'code'=>"cs"
    ],
    'da'=>[
        'name'=>"Danish",
        'ko'=>"덴마크어",
        'en'=>"Danish",
        'ja'=>"デンマーク語",
        'fr'=>"danois",
        'de'=>"Dänisch",
        'code'=>"da"
    ],
    'de'=>[
        'name'=>"Deutsch",
        'ko'=>"독일어",
        'en'=>"German",
        'ja'=>"ドイツ語",
        'fr'=>"allemand",
        'de'=>"Deutsch",
        'code'=>"de"
    ],
    'el'=>[
        'name'=>"Greek",
        'ko'=>"그리스어",
        'en'=>"Greek",
        'ja'=>"ギリシャ語",
        'fr'=>"grec",
        'de'=>"Griechisch",
        'code'=>"el"
    ],
    'en'=>[
        'name'=>"English",
        'ko'=>"영어",
        'en'=>"English",
        'ja'=>"英語",
        'fr'=>"anglais",
        'de'=>"Englisch",
        'code'=>"en"
    ],
    'et'=>[
        'name'=>"Estonian",
        'ko'=>"에스토니아어",
        'en'=>"Estonian",
        'ja'=>"エストニア語",
        'fr'=>"estonien",
        'de'=>"Estnisch",
        'code'=>"et"
    ],
    'es'=>[
        'name'=>"Español",
        'ko'=>"스페인어",
        'en'=>"Spanish",
        'ja'=>"スペイン語",
        'fr'=>"espagnol",
        'de'=>"Spanisch",
        'code'=>"es"
    ],
    'fi'=>[
        'name'=>"Finnish",
        'ko'=>"핀란드어",
        'en'=>"Finnish",
        'ja'=>"フィンランド語",
        'fr'=>"finnois",
        'de'=>"Finnisch",
        'code'=>"fi"
    ],
    'fr'=>[
        'name'=>"Français",
        'ko'=>"프랑스어",
        'en'=>"French",
        'ja'=>"フランス語",
        'fr'=>"français",
        'de'=>"Französisch",
        'code'=>"fr"
    ],
    'ga'=>[
        'name'=>"Irish",
        'ko'=>"아일랜드어",
        'en'=>"Irish",
        'ja'=>"アイルランド語",
        'fr'=>"irlandais",
        'de'=>"Irischer",
        'code'=>"ga"
    ],
    'hi'=>[
        'name'=>"Hindi",
        'ko'=>"힌디어",
        'en'=>"Hindi",
        'ja'=>"ヒンディー語",
        'fr'=>"hindi",
        'de'=>"Hindi",
        'code'=>"hi"
    ],
    'hu'=>[
        'name'=>"Hungarian",
        'ko'=>"헝가리어",
        'en'=>"Hungarian",
        'ja'=>"ハンガリー語",
        'fr'=>"hongrois",
        'de'=>"Ungarisch",
        'code'=>"hu"
    ],
    'he'=>[
        'name'=>"Hebrew",
        'ko'=>"히브리어",
        'en'=>"Hebrew",
        'ja'=>"ヘブロイア語",
        'fr'=>"hébreu",
        'de'=>"Hebräisch",
        'code'=>"he"
    ],
    'it'=>[
        'name'=>"Italian",
        'ko'=>"이탈리아어",
        'en'=>"Italian",
        'ja'=>"イタリア語",
        'fr'=>"italien",
        'de'=>"Italienisch",
        'code'=>"it"
    ],
    'ja'=>[
        'name'=>"日本語",
        'ko'=>"일본어",
        'en'=>"Japanese",
        'ja'=>"日本語",
        'fr'=>"japonais",
        'de'=>"Japanisch",
        'code'=>"ja"
    ],
    'ko'=>[
        'name'=>"한국어",
        'ko'=>"한국어",
        'en'=>"Korean",
        'ja'=>"韓国語",
        'fr'=>"coréen",
        'de'=>"Koreanisch",
        'code'=>"ko"
    ],
    'lv'=>[
        'name'=>"Latvian",
        'ko'=>"라트비아어",
        'en'=>"Latvian",
        'ja'=>"ラトビア語",
        'fr'=>"letton",
        'de'=>"Lettisch",
        'code'=>"lv"
    ],
    'lt'=>[
        'name'=>"Lithuanian",
        'ko'=>"리투아니아어",
        'en'=>"Lithuanian",
        'ja'=>"リトアニア語",
        'fr'=>"lituanien",
        'de'=>"Litauisch",
        'code'=>"lt"
    ],
    'nl'=>[
        'name'=>"Dutch",
        'ko'=>"네덜란드어",
        'en'=>"Dutch",
        'ja'=>"オランダ語",
        'fr'=>"néerlandais",
        'de'=>"Niederländisch",
        'code'=>"nl"
    ],
    'no'=>[
        'name'=>"Norwegian",
        'ko'=>"노르웨이어",
        'en'=>"Norwegian",
        'ja'=>"ノルウェー語",
        'fr'=>"norvégien",
        'de'=>"Norwegisch",
        'code'=>"no"
    ],
    'pl'=>[
        'name'=>"Polish",
        'ko'=>"폴란드어",
        'en'=>"Polish",
        'ja'=>"ポーランド語",
        'fr'=>"polonais",
        'de'=>"Polnisch",
        'code'=>"pl"
    ],
    'pt'=>[
        'name'=>"Portuguese",
        'ko'=>"포르투갈어",
        'en'=>"Portuguese",
        'ja'=>"ポルトガル語",
        'fr'=>"portugais",
        'de'=>"Portugiesisch",
        'code'=>"pt"
    ],
    'sv'=>[
        'name'=>"Swedish",
        'ko'=>"스웨덴어",
        'en'=>"Swedish",
        'ja'=>"スウェーデン語",
        'fr'=>"suédois",
        'de'=>"Schwedisch",
        'code'=>"sv"
    ],
    'ro'=>[
        'name'=>"Romanian",
        'ko'=>"루마니아어",
        'en'=>"Romanian",
        'ja'=>"ルーマニア語",
        'fr'=>"roumain",
        'de'=>"Rumänisch",
        'code'=>"ro"
    ],
    'ru'=>[
        'name'=>"Russian",
        'ko'=>"러시아어",
        'en'=>"Russian",
        'ja'=>"ロシア語",
        'fr'=>"russe",
        'de'=>"Russisch",
        'code'=>"ru"
    ],
    'sr'=>[
        'name'=>"Serbian",
        'ko'=>"세르비아어",
        'en'=>"Serbian",
        'ja'=>"セルビア語",
        'fr'=>"serbe",
        'de'=>"Serbisch",
        'code'=>"sr-CS"
    ],
    'sk'=>[
        'name'=>"Slovak",
        'ko'=>"슬로바키아어",
        'en'=>"Slovak",
        'ja'=>"スロバキア語",
        'fr'=>"slovaque",
        'de'=>"Slowakisch",
        'code'=>"sk"
    ],
    'sl'=>[
        'name'=>"Slovenian",
        'ko'=>"슬로베니아어",
        'en'=>"Slovenian",
        'ja'=>"スロベニア語",
        'fr'=>"slovène",
        'de'=>"Slowenisch",
        'code'=>"sl"
    ],
    'th'=>[
        'name'=>"Thai",
        'ko'=>"태국어",
        'en'=>"Thai",
        'ja'=>"タイ語",
        'fr'=>"thaï",
        'de'=>"Thai",
        'code'=>"th"
    ],
    'tr'=>[
        'name'=>"Turkish",
        'ko'=>"터키어",
        'en'=>"Turkish",
        'ja'=>"トルコ語",
        'fr'=>"turc",
        'de'=>"Türkisch",
        'code'=>"tr"
    ],
    'uk'=>[
        'name'=>"Ukrainian",
        'ko'=>"우크라이나어",
        'en'=>"Ukrainian",
        'ja'=>"ウクライナ語",
        'fr'=>"ukrainien",
        'de'=>"Ukrainisch",
        'code'=>"uk-UA"
    ],
    'zh'=>[
        'name'=>"简体中文",
        'ko'=>"중국어(간체)",
        'en'=>"Chinese (Simplified)",
        'ja'=>"中国語(簡体字)",
        'fr'=>"chinois simplifié",
        'de'=>"Chinesisch (Vereinfacht)",
        'code'=>"zh-chs"
    ],
    'zh'=>[
        'name'=>"繁體中文",
        'ko'=>"중국어(번체)",
        'en'=>"Chinese (Traditional)",
        'ja'=>"中国語(繁体字)",
        'fr'=>"chinois traditionnel",
        'de'=>"Chinesisch (Traditionell)",
        'code'=>"zh-cht"
    ]

];
